# Generated by Django 5.2.7 on 2025-10-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', '-total_price', 'user__username', '-updated_at', '-created_at']},
        ),
    ]
