# Generated by Django 5.2.7 on 2025-11-09 17:41

import apps.order.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique token used to identify anonymous carts via cookie.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.order.models.default_order_token_expiry, help_text='Token expiration; anonymous carts past this date may be culled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', '-total_price', '-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_orders', to='order.ordertoken'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('token__isnull', True)), models.Q(('user__isnull', True), ('token__isnull', False)), _connector='OR'), name='order_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Cart'), ('user__isnull', False)), fields=('user', 'status'), name='unique_cart_order_per_user'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Cart'), ('token__isnull', False)), fields=('token', 'status'), name='unique_cart_order_per_token'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'Cart'), models.Q(('status__in', ['Pending', 'Paid', 'Shipped', 'Delivered', 'Completed']), ('user__isnull', False)), _connector='OR'), name='only_authenticated_can_have_non_cart_status'),
        ),
    ]
