# Generated by Django 5.2.7 on 2025-10-24 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_item', to='order.inventory'),
        ),
    ]
