# Generated by Django 5.2.7 on 2025-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_shipping_address_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserve_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reserve_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
