# Generated by Django 5.2.7 on 2025-11-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_reserve_expires_at_order_reserve_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-stock', 'price', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', '-updated_at']},
        ),
    ]
