# Generated by Django 5.2.7 on 2025-10-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-inventory__price', '-quantity']},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='inventory',
        ),
    ]
