# Generated by Django 5.2.7 on 2025-11-16 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options_product_is_active'),
        ('review', '0002_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(condition=models.Q(('parent__isnull', True)), fields=['author', 'product'], name='unique_root_review'),
        ),
    ]
