# Generated by Django 5.2.7 on 2025-10-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
