# Generated by Django 5.2.7 on 2025-11-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_display_name', '-updated_at']},
        ),
    ]
